DO $$ BEGIN
    CREATE TYPE role AS ENUM ('ADMIN', 'STAFF', 'TEACHING', 'STUDENT', 'OFFICE_STAFF', 'APPLICANT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role role NOT NULL,
  profile_image TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
